version: '3.7'
services:
  gse:
    image: gse-insurance:prod-1
    ports:
      - "8080:$PORT"
    environment:
      PORT: $PORT
      NODE_ENV: production
      SECRET_KEY: $SECRET_KEY
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
      driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
