import { companySizes } from "./client";

export const labels = {
  index: "מס' פוליסה",
  messages: "הודעות",
  type: "סוג הביטוח",
  author: "לקוח",
  status: "סטטוס",
  assetDescription: "תיאור הנכס",
  companyDescription: "תיאור החברה",
  insuranceDuration: "תקופת ביטוח מבוקשת",
  maxPrice: "פרמיה מירבית מבוקשת",
  tenderFinalDate: "תקופת המכרז הרצויה",
  amountOfOffers: "כמות הצעות",
  comments: "הערות",
  wasInsuredOneYearAgo: "האם הנכס היה מבוטח בשנה האחרונה",
  wasInsuredTwoYearsAgo: "האם הנכס היה מבוטח בשנתיים האחרונות",
  createdAt: "זמן יצירה",
  startDate: "מועד סיום המכרז",
  activeTime: "מועד תחילת הפוליסה",
  endTime: "מועד סיום הפוליסה",
  endTimeRelative: "מועד סיום הפוליסה",
  startDateRelative: "מועד סיום המכרז",
  activeTimeRelative: "מועד תחילת הפוליסה",
  firstAccept: "אישור A",
  secondAccept: "אישור B",
  password: "סיסמה",
  name: "שם החברה",
  email: "אימייל",
  username: "שם משתמש",
  companyId: 'ח"פ של החברה',
  address: "כתובת",
  phoneNumber: "מספר פלאפון",
  owner: "בעלים",
  fieldOfActivity: "תחומי פעילות",
  contactName: "איש קשר",
  contactPhone: "פלאפון איש קשר",
  contactEmail: "אימייל איש קשר",
  notifyTime: "זמן התראה",
  companyType: "סוג החברה",
  companySize: "מחזור הכנסות שנתי",
  rePassword: "אימות סיסמה",
}
