export const labels = {
  index: "מס' פוליסה",
  messages: "הודעות",
  type: "סוג הביטוח",
  author: "יוצר",
  status: "סטטוס",
  assetDescription: "תיאור הנכס",
  companyDescription: "תיאור החברה",
  insuranceDuration: "משך הביטוח",
  maxPrice: "פרמיה מקסימלית",
  comments: "הערות",
  isCurrentlyInsured: "מבוטח כרגע",
  createdAt: "זמן יצירה",
  startDate: "זמן התחלה",
  activeTime: "תאריך העמדה",
  firstAccept: "אישור A",
  secondAccept: "אישור B",
  password: "סיסמה",
  name: "שם",
  emaik: "אימייל",
}
